# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
import sys

from PyQt5 import QtCore, QtGui, QtWidgets

UI_DIR = os.path.abspath(os.path.dirname(__file__))
PROJECT_DIR = os.path.abspath(os.path.join(UI_DIR, '..'))

sys.path = [
    path for path in sys.path
    if os.path.abspath(path or os.getcwd()) != UI_DIR
]
sys.path.insert(0, PROJECT_DIR)

from cipher.rsa import RSACipher


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.rsa_cipher = RSACipher()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 683)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 40, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 150, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 330, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(570, 150, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(580, 340, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.plain_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plain_text.setGeometry(QtCore.QRect(220, 160, 281, 71))
        self.plain_text.setObjectName("plain_text")
        self.information_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.information_text.setGeometry(QtCore.QRect(800, 160, 281, 71))
        self.information_text.setObjectName("information_text")
        self.cipher_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.cipher_text.setGeometry(QtCore.QRect(220, 320, 281, 71))
        self.cipher_text.setObjectName("cipher_text")
        self.signature_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.signature_text.setGeometry(QtCore.QRect(800, 320, 281, 71))
        self.signature_text.setObjectName("signature_text")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(310, 480, 81, 31))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(480, 490, 81, 31))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(650, 480, 81, 31))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify.setGeometry(QtCore.QRect(860, 480, 81, 31))
        self.btn_verify.setObjectName("btn_verify")
        self.btn_generate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generate.setGeometry(QtCore.QRect(80, 480, 131, 31))
        self.btn_generate.setObjectName("btn_generate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.connect_events()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA DEMO CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Plain Text"))
        self.label_3.setText(_translate("MainWindow", "Cipher Text"))
        self.label_4.setText(_translate("MainWindow", "Information"))
        self.label_5.setText(_translate("MainWindow", "Signature"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.btn_verify.setText(_translate("MainWindow", "Verify"))
        self.btn_generate.setText(_translate("MainWindow", "Generate Key"))

    def connect_events(self):
        self.btn_generate.clicked.connect(self.generate_key)
        self.btn_encrypt.clicked.connect(self.encrypt_message)
        self.btn_decrypt.clicked.connect(self.decrypt_message)
        self.btn_sign.clicked.connect(self.sign_message)
        self.btn_verify.clicked.connect(self.verify_signature)

    def show_error(self, message):
        QtWidgets.QMessageBox.warning(None, "RSA Error", message)

    def generate_key(self):
        self.rsa_cipher.generate_key()
        self.information_text.setPlainText("Keys generated successfully")

    def encrypt_message(self):
        message = self.plain_text.toPlainText()
        if not message:
            self.show_error("Please enter plain text.")
            return

        try:
            public_key, _ = self.rsa_cipher.load_key()
            encrypted_message = self.rsa_cipher.encrypt(message, public_key)
        except FileNotFoundError:
            self.show_error("Please generate keys first.")
            return
        except Exception as error:
            self.show_error(str(error))
            return

        self.cipher_text.setPlainText(encrypted_message.hex())
        self.information_text.setPlainText("Encrypted successfully")

    def decrypt_message(self):
        ciphertext_hex = self.cipher_text.toPlainText().strip()
        if not ciphertext_hex:
            self.show_error("Please enter cipher text.")
            return

        try:
            ciphertext = bytes.fromhex(ciphertext_hex)
            _, private_key = self.rsa_cipher.load_key()
            decrypted_message = self.rsa_cipher.decrypt(ciphertext, private_key)
        except ValueError:
            self.show_error("Cipher text must be a hex string.")
            return
        except FileNotFoundError:
            self.show_error("Please generate keys first.")
            return
        except Exception as error:
            self.show_error(str(error))
            return

        if decrypted_message is False:
            self.show_error("Can not decrypt this cipher text.")
            return

        self.plain_text.setPlainText(decrypted_message)
        self.information_text.setPlainText("Decrypted successfully")

    def sign_message(self):
        message = self.plain_text.toPlainText()
        if not message:
            self.show_error("Please enter plain text.")
            return

        try:
            _, private_key = self.rsa_cipher.load_key()
            signature = self.rsa_cipher.sign(message, private_key)
        except FileNotFoundError:
            self.show_error("Please generate keys first.")
            return
        except Exception as error:
            self.show_error(str(error))
            return

        self.signature_text.setPlainText(signature.hex())
        self.information_text.setPlainText("Signed successfully")

    def verify_signature(self):
        message = self.plain_text.toPlainText()
        signature_hex = self.signature_text.toPlainText().strip()
        if not message or not signature_hex:
            self.show_error("Please enter plain text and signature.")
            return

        try:
            signature = bytes.fromhex(signature_hex)
            public_key, _ = self.rsa_cipher.load_key()
        except ValueError:
            self.show_error("Signature must be a hex string.")
            return
        except FileNotFoundError:
            self.show_error("Please generate keys first.")
            return
        except Exception as error:
            self.show_error(str(error))
            return

        if self.rsa_cipher.verify(message, signature, public_key):
            self.information_text.setPlainText("Signature is valid")
        else:
            self.information_text.setPlainText("Signature is invalid")


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
